language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'

before_script:
    - composer self-update
    - composer install --no-interaction

script:
    - vendor/bin/phpunit
    - vendor/bin/phpunit --testsuite unit --coverage-clover=coverage.clover

after_success:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    - bash <(curl -s https://codecov.io/bash)