services:
    app.callback_controller:
        class: AppBundle\Controller\CallbackController
        arguments:
            - '@app.webhook_handler'

    app.webhook_validator:
        class: AppBundle\Webhook\Validator\GithubValidator
        arguments:
            - '%kernel.secret%'

    app.webhook_validation_listener:
        class: AppBundle\EventListener\WebhookValidationListener
        arguments:
            - '@app.webhook_validator'
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    app.webhook_handler:
        class: AppBundle\Webhook\Handler
